### ISSUE TITLE
Render html with functions

### ISSUE THREAD

**Issue by tcitworld** [jshmrtn/vue3-gettext#19]
Since directives are now depreciated in 2.0.0-beta, what's the method to perform interpolation with HTML using functions?

Should there be a `render-html` option passed to the functions?

**Comment by lzurbriggen** [comment]
@tcitworld Unfortunately passing a `render-html` option will not work because the template compiler does not interpolate html, so this doesn't work: `<span>{{ "<b>Demo</b>" }}</span>`.

You will have to use **v-html**:
```vue
<span v-html="$gettext('<b>Demo</b>')"></span>
```

The XSS/security concerns of `v-html` don't apply if the translations are static, which they usually are. From the [vue docs](https://v2.vuejs.org/v2/guide/syntax#Raw-HTML):
> Only use HTML interpolation on trusted content and never on user-provided content.

**Comment by tcitworld** [comment]
Sorry, I should have been more explicit. My issue is when I use parameters to hide the complexity of the markup in the translation files, or want some attribute to be dynamic, something like this:
```vue
<h3 v-html="$ngettext(
            'Search for your XXX on %{tagStart}one website%{tagEnd} indexed by %{indexName}!',
            'Search for your XXX on %{tagStart}%{websitesCount} websites{%tagEnd%} indexed by %{indexName}!',
            websitesCount,
            { tagStart, tagEnd, indexName, websitesCount }
          )" />
```
Where
```js
const tagStart = `<a class="underline" href="${indexedWebsitesUrl}" target="_blank">`
```
The parameters are escaped.

**Comment by lzurbriggen** [comment]
@tcitworld Added a `disableHtmlEscaping` parameter to the functions in [v2.1.0](https://github.com/jshmrtn/vue3-gettext/releases/tag/v2.1.0)
